image: atlassian/default-image:4

options:
  size: 2x

definitions:
  services:
    docker:
      memory: 7128
      
pipelines:
  branches:
    develop:
      - step:
          name: Build & Push Docker Image
          script:
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - IMAGE_NAME=$BITBUCKET_REPO_SLUG
            - IMAGE=${DOCKERHUB_NAMESPACE}/${IMAGE_NAME}
            - SSH_KEY=$(umask  077 ; echo $SSH_PRIVATE_KEY | base64 --decode)
            - echo "$SSH_KEY" > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            - export DOCKER_BUILDKIT=1
            - npm run docker:build:dev
            - npm run docker:push:dev
          services:
            - docker

    master:
      - step:
          name: Build & Push Docker Image
          script:
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - IMAGE_NAME=$BITBUCKET_REPO_SLUG
            - IMAGE=${DOCKERHUB_NAMESPACE}/${IMAGE_NAME}
            - SSH_KEY=$(umask  077 ; echo $SSH_PRIVATE_KEY | base64 --decode)
            - echo "$SSH_KEY" > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            - export DOCKER_BUILDKIT=1
            - npm run docker:build:latest
            - npm run docker:push:latest
            - npm run docker:build:version
            - npm run docker:push:version
          services:
            - docker
