version: "3"
services:
  ee24-backoffice:
    image: newtral/ee24-backoffice:dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000
    container_name: ee24-backoffice
