version: '3'
services:
  backoffice-factcricis-svc:
    image: newtral/backoffice-factcricis-svc:dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - GOOGLE_OAUTH_ID=254095989607-19rbci1m32qsdb66e51514pmre9cgrds.apps.googleusercontent.com
    ports:
      - 3000:3000
    container_name: backoffice-factcricis-svc
